package twilightforest.client;

import net.minecraft.client.renderer.RenderType;
import net.minecraft.client.renderer.ItemBlockRenderTypes;

import net.fabricmc.fabric.api.blockrenderlayer.v1.BlockRenderLayerMap;
import twilightforest.block.TFBlocks;

public class RenderLayerRegistration {
	public static void init() {
		RenderType cutoutMipped = RenderType.cutoutMipped();
		RenderType cutout = RenderType.cutout();
		RenderType translucent = RenderType.translucent();
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.TWILIGHT_OAK_LEAVES, cutoutMipped);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.RAINBOW_OAK_LEAVES, cutoutMipped);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.CANOPY_LEAVES, cutoutMipped);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.MANGROVE_LEAVES, cutoutMipped);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.TIME_LEAVES, cutoutMipped);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.TRANSFORMATION_LEAVES, cutoutMipped);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.MINING_LEAVES, cutoutMipped);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.SORTING_LEAVES, cutoutMipped);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.TIME_DOOR, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.SORTING_DOOR, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.TIME_TRAPDOOR, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.SORTING_TRAPDOOR, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.TWILIGHT_PORTAL, translucent);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.AURORALIZED_GLASS, translucent);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.THORN_ROSE, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.FIERY_BLOCK, translucent);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.THORN_LEAVES, cutoutMipped);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.BEANSTALK_LEAVES, cutoutMipped);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.GIANT_LEAVES, cutoutMipped);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.EXPERIMENT_115, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.WISPY_CLOUD, translucent);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.UBEROUS_SOIL, translucent);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.TROLLVIDR, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.UNRIPE_TROLLBER, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.TROLLBER, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.HUGE_LILY_PAD, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.HUGE_WATER_LILY, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.YELLOW_CASTLE_RUNE_BRICK, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.VIOLET_CASTLE_RUNE_BRICK, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.PINK_CASTLE_RUNE_BRICK, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.BLUE_CASTLE_RUNE_BRICK, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.YELLOW_CASTLE_DOOR, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.VIOLET_CASTLE_DOOR, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.PINK_CASTLE_DOOR, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.BLUE_CASTLE_DOOR, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.GREEN_THORNS, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.BROWN_THORNS, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.BURNT_THORNS, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.TWILIGHT_PORTAL_MINIATURE_STRUCTURE, cutout);
//		RenderTypeLookup.setRenderLayer(TFBlocks.HEDGE_MAZE_MINIATURE_STRUCTURE, cutout);
//		RenderTypeLookup.setRenderLayer(TFBlocks.HOLLOW_HILL_MINIATURE_STRUCTURE, cutout);
//		RenderTypeLookup.setRenderLayer(TFBlocks.QUEST_GROVE_MINIATURE_STRUCTURE, cutout);
//		RenderTypeLookup.setRenderLayer(TFBlocks.MUSHROOM_TOWER_MINIATURE_STRUCTURE, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.NAGA_COURTYARD_MINIATURE_STRUCTURE, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.LICH_TOWER_MINIATURE_STRUCTURE, cutout);
//		RenderTypeLookup.setRenderLayer(TFBlocks.MINOTAUR_LABYRINTH_MINIATURE_STRUCTURE, cutout);
//		RenderTypeLookup.setRenderLayer(TFBlocks.HYDRA_LAIR_MINIATURE_STRUCTURE, cutout);
//		RenderTypeLookup.setRenderLayer(TFBlocks.GOBLIN_STRONGHOLD_MINIATURE_STRUCTURE, cutout);
//		RenderTypeLookup.setRenderLayer(TFBlocks.DARK_TOWER_MINIATURE_STRUCTURE, cutout);
//		RenderTypeLookup.setRenderLayer(TFBlocks.YETI_CAVE_MINIATURE_STRUCTURE, cutout);
//		RenderTypeLookup.setRenderLayer(TFBlocks.AURORA_PALACE_MINIATURE_STRUCTURE, cutout);
//		RenderTypeLookup.setRenderLayer(TFBlocks.TROLL_CAVE_COTTAGE_MINIATURE_STRUCTURE, cutout);
//		RenderTypeLookup.setRenderLayer(TFBlocks.FINAL_CASTLE_MINIATURE_STRUCTURE, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.TROPHY_PEDESTAL, translucent);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.TWISTED_STONE_PILLAR, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.CANDELABRA, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.FIERY_BLOCK, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.FIREFLY_JAR, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.FIREFLY_SPAWNER, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.CICADA_JAR, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.MOSS_PATCH, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.MAYAPPLE, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.CLOVER_PATCH, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.FIDDLEHEAD, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.MUSHGLOOM, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.TORCHBERRY_PLANT, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.ROOT_STRAND, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.FALLEN_LEAVES, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.UNCRAFTING_TABLE, translucent);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.ENCASED_SMOKER, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.ENCASED_FIRE_JET, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.TWILIGHT_OAK_SAPLING, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.RAINBOW_OAK_SAPLING, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.CANOPY_SAPLING, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.MANGROVE_SAPLING, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.DARKWOOD_SAPLING, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.HOLLOW_OAK_SAPLING, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.TIME_SAPLING, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.TRANSFORMATION_SAPLING, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.MINING_SAPLING, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.SORTING_SAPLING, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.BUILT_BLOCK, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.ANTIBUILT_BLOCK, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.REACTOR_DEBRIS, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.PINK_FORCE_FIELD, translucent);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.BLUE_FORCE_FIELD, translucent);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.GREEN_FORCE_FIELD, translucent);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.VIOLET_FORCE_FIELD, translucent);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.ORANGE_FORCE_FIELD, translucent);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.NAGA_BOSS_SPAWNER, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.LICH_BOSS_SPAWNER, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.HYDRA_BOSS_SPAWNER, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.UR_GHAST_BOSS_SPAWNER, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.KNIGHT_PHANTOM_BOSS_SPAWNER, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.SNOW_QUEEN_BOSS_SPAWNER, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.MINOSHROOM_BOSS_SPAWNER, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.ALPHA_YETI_BOSS_SPAWNER, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.FINAL_BOSS_BOSS_SPAWNER, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.REAPPEARING_BLOCK, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.LOCKED_VANISHING_BLOCK, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.VANISHING_BLOCK, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.CARMINITE_BUILDER, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.ANTIBUILDER, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.CARMINITE_REACTOR, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.GHAST_TRAP, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.POTTED_TWILIGHT_OAK_SAPLING, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.POTTED_CANOPY_SAPLING, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.POTTED_MANGROVE_SAPLING, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.POTTED_DARKWOOD_SAPLING, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.POTTED_HOLLOW_OAK_SAPLING, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.POTTED_RAINBOW_OAK_SAPLING, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.POTTED_TIME_SAPLING, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.POTTED_TRANSFORMATION_SAPLING, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.POTTED_MINING_SAPLING, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.POTTED_SORTING_SAPLING, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.POTTED_MAYAPPLE, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.POTTED_FIDDLEHEAD, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.POTTED_MUSHGLOOM, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.POTTED_THORN, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.POTTED_GREEN_THORN, cutout);
		BlockRenderLayerMap.INSTANCE.putBlock(TFBlocks.POTTED_DEAD_THORN, cutout);
	}
}
